# Generated by Django 4.1.7 on 2023-03-02 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='followed_users',
            field=models.ManyToManyField(null=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
